# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2023-07-27 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='statement_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
