# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-09-07 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='objectType',
            field=models.CharField(blank=True, default='Activity', max_length=8),
        ),
        migrations.AlterField(
            model_name='activityprofile',
            name='profile',
            field=models.FileField(null=True, upload_to='activity_profile'),
        ),
        migrations.AlterField(
            model_name='activitystate',
            name='state',
            field=models.FileField(null=True, upload_to='activity_state'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='objectType',
            field=models.CharField(blank=True, default='Agent', max_length=6),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='profile',
            field=models.FileField(null=True, upload_to='agent_profile'),
        ),
        migrations.AlterField(
            model_name='statementattachment',
            name='payload',
            field=models.FileField(null=True, upload_to='attachment_payloads'),
        ),
        migrations.AlterField(
            model_name='statementref',
            name='object_type',
            field=models.CharField(default='StatementRef', max_length=12),
        ),
    ]
