# Generated by Django 3.2.22 on 2023-10-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrs', '0002_auto_20230907_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='result_completion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='result_success',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='voided',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='substatement',
            name='result_completion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='substatement',
            name='result_success',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
