# Generated by Django 3.2.23 on 2023-12-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lrs", "0003_auto_20231025_0756"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS idx_canonical_activity 
            ON lrs_activity 
            USING btree (activity_id, canonical_version) 
            WHERE canonical_version
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_canonical_activity",
            state_operations=[
                migrations.AddIndex(
                    model_name="activity",
                    index=models.Index(
                        condition=models.Q(("canonical_version__isnull", False)),
                        fields=["activity_id", "canonical_version"],
                        name="idx_canonical_activity",
                    ),
                )
            ],
        ),
    ]
