# Generated by Django 3.2.23 on 2023-12-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lrs", "0004_activity_idx_canonical_activity"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="activity",
            name="idx_canonical_activity",
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                name="idx_activity_authority_canonic",  # 30 char max length
                fields=["activity_id", "authority_id", "canonical_version"],
            ),
        ),
    ]
