# Generated by Django 4.2.10 on 2024-03-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrs', '0005_auto_20231220_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='member',
            field=models.ManyToManyField(null=True, related_name='agents', to='lrs.agent'),
        ),
    ]