# Generated by Django 4.2.11 on 2024-10-29 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lrs', '0006_alter_agent_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='context_instructor',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_context_instructor', to='lrs.agent'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='context_team',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_context_team', to='lrs.agent'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='object_agent',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_of_statement', to='lrs.agent'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='object_statementref',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_of_statement', to='lrs.statementref'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='object_substatement',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_of_statement', to='lrs.substatement'),
        ),
    ]
