# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2023-07-21 09:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('key', models.CharField(max_length=256)),
                ('secret', models.CharField(blank=True, max_length=2048)),
                ('rsa_signature', models.BooleanField(default=False)),
                ('status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Canceled'), (4, 'Rejected')], default=1)),
                ('xauth_allowed', models.BooleanField(default=False, verbose_name=b'Allow xAuth')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_key', models.CharField(max_length=32)),
                ('consumer_key', models.CharField(max_length=256)),
                ('key', models.CharField(max_length=255)),
                ('timestamp', models.PositiveIntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=32, null=True)),
                ('secret', models.CharField(blank=True, max_length=2048, null=True)),
                ('token_type', models.SmallIntegerField(choices=[(1, 'Request'), (2, 'Access')])),
                ('timestamp', models.IntegerField(default=1689933315L)),
                ('is_approved', models.BooleanField(default=False)),
                ('scope', models.CharField(default=b'statements/write statements/read/mine', max_length=100)),
                ('verifier', models.CharField(max_length=10)),
                ('callback', models.CharField(blank=True, max_length=2083, null=True)),
                ('callback_confirmed', models.BooleanField(default=False)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_provider.Consumer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
