# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-09-07 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='xauth_allowed',
            field=models.BooleanField(default=False, verbose_name='Allow xAuth'),
        ),
        migrations.AlterField(
            model_name='token',
            name='scope',
            field=models.CharField(default='statements/write statements/read/mine', max_length=100),
        ),
    ]
